
server:
  port: 8083

eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    fetch-registry: true



#zuul:
#  routes:
#    feign-service:
#      path: /feign/**
#      serviceId: feign



#feign:
#  ribbon:
#    ConnectTimeout: 2000
#    ReadTimeout: 3000
#    eureka:
#      enabled: true
#    listOfServers: 127.0.0.1:8082


spring:
  application:
    name: zuul

debug: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
