server:
  port: 7000




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Chengpanfei/Spring-Cloud-Config-Repo.git
          search-paths: /
          username: 643842536@qq.com
          password: ${env.GIT_SERCET}